"""
Profile Manager - Handles MO2 profile operations
"""

import os
from pathlib import Path
import shutil


class ProfileManager:
    """Manages Mod Organizer 2 profiles"""
    
    def __init__(self, mo2_path=None):
        """Initialize the profile manager
        
        Args:
            mo2_path: Path to MO2 installation (optional)
        """
        self.mo2_path = mo2_path or os.getcwd()
        self.profiles_path = Path(self.mo2_path) / "profiles"
        
    def list_profiles(self):
        """List all available profiles
        
        Returns:
            List of profile names
        """
        if not self.profiles_path.exists():
            return []
        
        profiles = []
        for item in self.profiles_path.iterdir():
            if item.is_dir():
                profiles.append(item.name)
        
        return sorted(profiles)
    
    def create_profile(self, profile_name):
        """Create a new profile with all required MO2 profile files.
        
        Args:
            profile_name: Name of the profile to create
        """
        profile_path = self.profiles_path / profile_name
        
        if profile_path.exists():
            raise ValueError(f"Profile '{profile_name}' already exists")
        
        profile_path.mkdir(parents=True, exist_ok=True)
        
        # modlist.txt — enabled/disabled mod list
        (profile_path / "modlist.txt").write_text(
            f"# Modlist for profile: {profile_name}\n", encoding="utf-8"
        )
        # plugins.txt — enabled/disabled plugin list (MO2 format)
        (profile_path / "plugins.txt").write_text(
            "# This file was automatically generated by Mossy Manager\n",
            encoding="utf-8",
        )
        # loadorder.txt — plugin load order
        (profile_path / "loadorder.txt").write_text(
            "# This file was automatically generated by Mossy Manager\n",
            encoding="utf-8",
        )
        
        return True
    
    def delete_profile(self, profile_name):
        """Delete a profile
        
        Args:
            profile_name: Name of the profile to delete
        """
        profile_path = self.profiles_path / profile_name
        
        if not profile_path.exists():
            raise ValueError(f"Profile '{profile_name}' not found")
        
        shutil.rmtree(profile_path)
        return True
    
    def switch_profile(self, profile_name):
        """Switch to a different profile, persisting the selection.
        
        Args:
            profile_name: Name of the profile to switch to
        """
        profile_path = self.profiles_path / profile_name
        
        if not profile_path.exists():
            raise ValueError(f"Profile '{profile_name}' not found")
        
        # Persist the active profile in a marker file next to the profiles dir
        active_file = self.profiles_path / "_active_profile.txt"
        active_file.write_text(profile_name, encoding="utf-8")
        return True
    
    def get_active_profile(self):
        """Return the currently active profile name, or None if not set."""
        active_file = self.profiles_path / "_active_profile.txt"
        if active_file.exists():
            return active_file.read_text(encoding="utf-8").strip()
        return None
    
    def get_profile_info(self, profile_name):
        """Get information about a profile.
        
        Args:
            profile_name: Name of the profile
            
        Returns:
            Dictionary with profile information
        """
        profile_path = self.profiles_path / profile_name
        
        if not profile_path.exists():
            raise ValueError(f"Profile '{profile_name}' not found")
        
        info = {
            "name": profile_name,
            "path": str(profile_path),
            "exists": True,
        }
        
        modlist_file = profile_path / "modlist.txt"
        info["has_modlist"] = modlist_file.exists()
        if modlist_file.exists():
            mod_lines = [l for l in modlist_file.read_text(encoding="utf-8").splitlines()
                         if l.strip() and not l.strip().startswith("#")]
            info["mod_count"] = len(mod_lines)

        plugins_file = profile_path / "plugins.txt"
        info["has_plugins"] = plugins_file.exists()
        if plugins_file.exists():
            plugin_lines = [l for l in plugins_file.read_text(encoding="utf-8").splitlines()
                            if l.strip() and not l.strip().startswith("#")]
            info["plugin_count"] = len(plugin_lines)

        loadorder_file = profile_path / "loadorder.txt"
        info["has_loadorder"] = loadorder_file.exists()
        if loadorder_file.exists():
            lo_lines = [l for l in loadorder_file.read_text(encoding="utf-8").splitlines()
                        if l.strip() and not l.strip().startswith("#")]
            info["loadorder_count"] = len(lo_lines)

        return info
