"""
ScriptWriter — Advanced script generation for Fallout 4 mod management.

Generates ready-to-use scripts from structured problem descriptions, optionally
driven by a ``ReasoningResult`` from ``ModReasoner`` so the scripts are
*motivated* by actual analysis rather than boilerplate.

Script types produced
---------------------
1. **xEdit Pascal scripts** (.pas)
   - Conflict-resolution patches (forward winning records)
   - Batch record editors (rename, flag, clean ITMs)
   - Dependency checkers

2. **MO2 INI-tweak scripts** (.ini fragment)
   - Papyrus log enable
   - Archive invalidation
   - Performance tuning presets

3. **Batch / PowerShell scripts** (.bat / .ps1)
   - Safe-launch wrappers (launch via F4SE, not Steam)
   - Profile backup automation
   - Plugin-cap check before launch

All generated scripts include a header comment explaining what they do and
*why* they were generated (linked to the reasoning trace when available).
"""

from __future__ import annotations

import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# Import ReasoningResult lazily to avoid circular imports when used standalone
try:
    from mossy_manager.ai.reasoner import ReasoningResult
    _REASONER_AVAILABLE = True
except ImportError:  # pragma: no cover
    _REASONER_AVAILABLE = False
    ReasoningResult = None  # type: ignore[misc,assignment]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _safe_name(name: str) -> str:
    """Convert a human-readable name to a valid Pascal/file identifier."""
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if cleaned and cleaned[0].isdigit():
        cleaned = "Patch_" + cleaned
    return cleaned or "MossyPatch"


def _header_comment(
    script_type: str,
    description: str,
    reasoning_summary: Optional[str] = None,
    comment_char: str = "//",
) -> str:
    line = comment_char + " " + "=" * 70
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        line,
        f"{comment_char} Generated by Mossy Manager ScriptWriter — {now}",
        f"{comment_char} Script type : {script_type}",
        f"{comment_char} Description : {description}",
    ]
    if reasoning_summary:
        lines.append(f"{comment_char} AI Reasoning: {reasoning_summary[:120]}")
    lines.append(line)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# xEdit Pascal script builders
# ---------------------------------------------------------------------------

def _xedit_conflict_patch(
    patch_name: str,
    plugins: List[str],
    conflicts: List[Dict[str, Any]],
    reasoning_summary: Optional[str] = None,
) -> str:
    """
    Generate a full xEdit Pascal script that:
    1. Creates a new patch plugin
    2. Loops over the conflicting plugins
    3. For each conflict, copies the winning record into the patch
    """
    safe = _safe_name(patch_name)

    # Build per-conflict forward-record block
    conflict_blocks: List[str] = []
    for i, conflict in enumerate(conflicts):
        resource = conflict.get("resource", f"unknown_{i}")
        mods = conflict.get("mods", [])
        category = conflict.get("category", "other")
        severity = conflict.get("severity", "medium")
        winner = mods[-1] if mods else "unknown"

        comment = (
            f"// [{severity.upper()}] {category}: '{resource}'\n"
            f"// Winner (loads last): {winner}\n"
            f"// Overridden by: {', '.join(mods[:-1]) if len(mods) > 1 else 'none'}"
        )
        conflict_blocks.append(
            f"  {comment}\n"
            f"  // TODO: Forward '{resource}' record from {winner} into {patch_name}.esp\n"
        )

    plugin_list_str = "\n".join(
        f"  AddRequiredMaster(patchPlugin, '{p.replace(chr(39), chr(39)+chr(39))}', False);"
        for p in plugins
    )
    conflict_section = "\n".join(conflict_blocks) if conflict_blocks else (
        "  // No specific conflicts to forward — verify manually."
    )

    header = _header_comment(
        "xEdit Pascal — Conflict Resolution Patch",
        f"Creates {patch_name}.esp and forwards winning records",
        reasoning_summary,
        comment_char="//",
    )

    return f"""{header}

unit {safe}_Script;

{{
  This script creates a conflict-resolution patch plugin for Fallout 4.
  Run it from the xEdit Script Runner (Tools > Apply Script).
  
  Mods in scope: {", ".join(plugins[:8])}{"..." if len(plugins) > 8 else ""}
  Conflicts to resolve: {len(conflicts)}
}}

var
  patchPlugin: IInterface;
  rec:         IInterface;
  masterFile:  IInterface;

function Initialize: integer;
begin
  Result := 0;
  AddMessage('[Mossy] Creating patch: {patch_name}.esp');

  patchPlugin := AddNewFileName('{patch_name}.esp', False);
  if not Assigned(patchPlugin) then begin
    AddMessage('[Mossy] ERROR: Could not create patch plugin');
    Result := 1;
    Exit;
  end;

  // Add required masters
{plugin_list_str}

  AddMessage('[Mossy] Patch plugin created. Forwarding records...');
end;

function Process(e: IInterface): integer;
var
  conflictWinner: IInterface;
  patchRec:       IInterface;
begin
  Result := 0;

  // Only process records from our conflicting plugins
  if not ContainsFile(e, patchPlugin) then Exit;

{conflict_section}

  // Copy record into patch and set override
  patchRec := wbCopyElementToFile(e, patchPlugin, False, True);
  if Assigned(patchRec) then
    AddMessage('[Mossy] Forwarded: ' + FullPath(patchRec));
end;

function Finalize: integer;
begin
  Result := 0;
  AddMessage('[Mossy] Done. Save {patch_name}.esp and place it AFTER all patched mods.');
end;

end.
"""


def _xedit_clean_itms(
    plugin_name: str,
    reasoning_summary: Optional[str] = None,
) -> str:
    """Generate an xEdit script that removes Identical-To-Master records."""
    safe = _safe_name(plugin_name)
    header = _header_comment(
        "xEdit Pascal — Clean ITM Records",
        f"Remove Identical-To-Master (ITM) records from {plugin_name}",
        reasoning_summary,
        comment_char="//",
    )
    return f"""{header}

unit {safe}_CleanITM;

{{
  Removes Identical-To-Master (ITM) records from {plugin_name}.
  ITMs are unnecessary overrides that inflate the plugin and cause
  compatibility issues with other mods.
  
  WARNING: Always back up your plugin before running this script.
}}

var
  removedCount: integer;

function Initialize: integer;
begin
  Result    := 0;
  removedCount := 0;
  AddMessage('[Mossy] Starting ITM clean for {plugin_name}');
end;

function Process(e: IInterface): integer;
begin
  Result := 0;
  if IsITM(e) then begin
    Remove(e);
    Inc(removedCount);
    AddMessage('[Mossy] Removed ITM: ' + FullPath(e));
  end;
end;

function Finalize: integer;
begin
  Result := 0;
  AddMessage('[Mossy] ITM clean complete. Removed ' + IntToStr(removedCount) + ' record(s).');
  AddMessage('[Mossy] Save the plugin and verify in xEdit.');
end;

end.
"""


def _xedit_esl_flag(
    plugins: List[str],
    reasoning_summary: Optional[str] = None,
) -> str:
    """Generate a script that ESL-flags a list of plugins to free plugin slots."""
    header = _header_comment(
        "xEdit Pascal — ESL-Flag Plugins",
        f"Flag {len(plugins)} plugin(s) as ESL to free slot usage",
        reasoning_summary,
        comment_char="//",
    )
    plugin_checks = "\n".join(
        f"  if (GetFileName(f) = '{p.replace(chr(39), chr(39)*2)}') then FlagAsESL(f);"
        for p in plugins
    )
    return f"""{header}

unit ESLFlag_Script;

{{
  ESL-flags the listed plugins so they no longer consume one of the
  255 available plugin slots.
  
  IMPORTANT: A plugin can only be safely ESL-flagged if it contains
  fewer than 2048 new Form IDs (new records added by the mod, not
  overrides). Verify this with xEdit before flagging.
  
  Plugins to flag ({len(plugins)}):
  {chr(10).join("  - " + p for p in plugins)}
}}

var
  i: integer;
  f: IInterface;

function Initialize: integer;
begin
  Result := 0;
  AddMessage('[Mossy] ESL-flagging {len(plugins)} plugin(s)...');
  for i := 0 to Pred(FileCount) do begin
    f := FileByIndex(i);
{plugin_checks}
  end;
  AddMessage('[Mossy] Done. Save all modified plugins.');
end;

function Process(e: IInterface): integer;
begin
  Result := 0;
end;

function Finalize: integer;
begin
  Result := 0;
end;

end.
"""


# ---------------------------------------------------------------------------
# INI tweak generator
# ---------------------------------------------------------------------------

_INI_PRESETS: Dict[str, Dict[str, str]] = {
    "papyrus_logging": {
        "[Papyrus]": "",
        "bEnableLogging": "1",
        "bEnableTrace": "1",
        "bLoadDebugInformation": "1",
        "iMaxAllocatedMemoryBytes": "786432",
    },
    "archive_invalidation": {
        "[Archive]": "",
        "bInvalidateOlderFiles": "1",
        "sResourceDataDirsFinal": "",
    },
    "performance_high": {
        "[General]": "",
        "uExterior Cell Buffer": "64",
        "[Display]": "",
        "fShadowDistance": "3000.0000",
        "iShadowMapResolutionPrimary": "2048",
    },
    "performance_low": {
        "[General]": "",
        "uExterior Cell Buffer": "36",
        "[Display]": "",
        "fShadowDistance": "2000.0000",
        "iShadowMapResolutionPrimary": "1024",
    },
}

_INI_PRESET_DESCRIPTIONS = {
    "papyrus_logging": "Enable Papyrus script logging for crash diagnosis",
    "archive_invalidation": "Enable archive invalidation (required for loose file mods)",
    "performance_high": "High-end performance settings for strong PCs",
    "performance_low": "Performance settings for lower-end PCs",
}


def _ini_tweak(
    preset: str,
    reasoning_summary: Optional[str] = None,
) -> str:
    """Generate an INI fragment for a known preset."""
    if preset not in _INI_PRESETS:
        available = ", ".join(_INI_PRESETS.keys())
        raise ValueError(f"Unknown INI preset '{preset}'. Available: {available}")

    desc = _INI_PRESET_DESCRIPTIONS.get(preset, preset)
    header_lines = [
        "; " + "=" * 68,
        f"; Mossy Manager INI Tweak — {desc}",
        f"; Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"; Paste these lines into Fallout4Custom.ini",
        f"; (My Documents\\My Games\\Fallout4\\Fallout4Custom.ini)",
    ]
    if reasoning_summary:
        header_lines.append(f"; AI Reasoning: {reasoning_summary[:100]}")
    header_lines.append("; " + "=" * 68)
    header = "\n".join(header_lines)

    body_lines: List[str] = []
    for key, val in _INI_PRESETS[preset].items():
        if key.startswith("["):
            body_lines.append(f"\n{key}")
        else:
            body_lines.append(f"{key}={val}")

    return header + "\n" + "\n".join(body_lines) + "\n"


# ---------------------------------------------------------------------------
# Batch / PowerShell script generators
# ---------------------------------------------------------------------------

def _bat_safe_launch(
    mo2_path: str = "C:\\Modding\\ModOrganizer2",
    f4se_path: str = "C:\\Games\\Fallout4\\f4se_loader.exe",
    reasoning_summary: Optional[str] = None,
) -> str:
    header = _header_comment(
        "Windows Batch — Safe F4SE Launch via MO2",
        "Launch Fallout 4 through F4SE from inside Mod Organizer 2",
        reasoning_summary,
        comment_char="REM",
    )
    return f"""{header}

@echo off
setlocal

REM ── Configuration ──────────────────────────────────────────────────────
set MO2_PATH={mo2_path}
set F4SE_EXE={f4se_path}

REM ── Plugin cap check ────────────────────────────────────────────────────
REM Count enabled plugins (lines starting with * in plugins.txt)
set PLUGINS_FILE=%APPDATA%\\..\\Local\\ModOrganizer\\Fallout4\\profiles\\Default\\plugins.txt
if not exist "%PLUGINS_FILE%" (
    echo [Mossy] Warning: Could not find plugins.txt at %PLUGINS_FILE%
    goto LAUNCH
)
for /f %%a in ('findstr /r "^[*]" "%PLUGINS_FILE%" ^| find /c /v ""') do set PLUGIN_COUNT=%%a
echo [Mossy] Enabled plugin count: %PLUGIN_COUNT%
if %PLUGIN_COUNT% GEQ 255 (
    echo [Mossy] ERROR: Plugin cap reached ^(%PLUGIN_COUNT%/255^). Game will not load!
    echo [Mossy] ESL-flag or merge plugins before launching.
    pause
    exit /b 1
)

:LAUNCH
REM ── Launch via F4SE ─────────────────────────────────────────────────────
if not exist "%F4SE_EXE%" (
    echo [Mossy] ERROR: F4SE not found at %F4SE_EXE%
    echo [Mossy] Download F4SE from https://f4se.silverlock.org/
    pause
    exit /b 1
)

echo [Mossy] Launching Fallout 4 via F4SE...
start "" "%F4SE_EXE%"
exit /b 0
"""


def _ps1_backup_profiles(
    mo2_path: str = "C:\\Modding\\ModOrganizer2",
    backup_root: str = "C:\\Modding\\Backups",
    keep: int = 5,
    reasoning_summary: Optional[str] = None,
) -> str:
    header = _header_comment(
        "PowerShell — Automated Profile Backup",
        "Back up all MO2 profiles and prune old backups",
        reasoning_summary,
        comment_char="#",
    )
    return f"""{header}

# Configuration
$MO2ProfilesPath = "{mo2_path}\\profiles"
$BackupRoot       = "{backup_root}"
$KeepCount        = {keep}

# Ensure backup root exists
if (-not (Test-Path $BackupRoot)) {{
    New-Item -ItemType Directory -Path $BackupRoot | Out-Null
}}

$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"

foreach ($profile in Get-ChildItem -Path $MO2ProfilesPath -Directory) {{
    $dest = Join-Path $BackupRoot ("$($profile.Name)_backup_$timestamp")
    Write-Host "[Mossy] Backing up profile: $($profile.Name)"
    Copy-Item -Path $profile.FullName -Destination $dest -Recurse

    # Prune: keep only the $KeepCount most recent backups for this profile
    $pattern  = "$($profile.Name)_backup_*"
    $existing = Get-ChildItem -Path $BackupRoot -Filter $pattern -Directory |
                Sort-Object Name -Descending
    $toDelete = $existing | Select-Object -Skip $KeepCount
    foreach ($old in $toDelete) {{
        Write-Host "[Mossy] Removing old backup: $($old.Name)"
        Remove-Item -Path $old.FullName -Recurse -Force
    }}
}}

Write-Host "[Mossy] Backup complete."
"""


# ---------------------------------------------------------------------------
# Public ScriptWriter class
# ---------------------------------------------------------------------------

class ScriptWriter:
    """
    Generate scripts for Fallout 4 mod management tasks.

    All methods return the script as a **string**.  Use ``write()`` to save
    to disk, or work with the string directly.

    Parameters
    ----------
    output_dir : Path, optional
        Default directory for ``write()`` calls.
    """

    XEDIT_SCRIPT_TYPES = frozenset(
        {"conflict_patch", "clean_itms", "esl_flag"}
    )
    INI_PRESETS = frozenset(_INI_PRESETS.keys())
    BATCH_TYPES = frozenset({"safe_launch", "backup_profiles"})

    def __init__(self, output_dir: Optional[Path] = None) -> None:
        self.output_dir = Path(output_dir) if output_dir else Path("./mossy_scripts")

    # ------------------------------------------------------------------ #
    #  xEdit Pascal scripts                                               #
    # ------------------------------------------------------------------ #

    def xedit_conflict_patch(
        self,
        patch_name: str,
        plugins: List[str],
        conflicts: Optional[List[Dict[str, Any]]] = None,
        reasoning: "Optional[ReasoningResult]" = None,
    ) -> str:
        """
        Generate a Pascal script that creates a conflict-resolution patch in xEdit.

        Parameters
        ----------
        patch_name : str
            Name for the generated ``.esp`` (e.g. ``"MyPatch"``).
        plugins : list of str
            Plugins involved in the conflicts.
        conflicts : list of dicts, optional
            Conflict dicts from ``ConflictResolver``.
        reasoning : ReasoningResult, optional
            Reasoning trace to embed in the script header.
        """
        rs = reasoning.conclusion if reasoning else None
        return _xedit_conflict_patch(patch_name, plugins, conflicts or [], rs)

    def xedit_clean_itms(
        self,
        plugin_name: str,
        reasoning: "Optional[ReasoningResult]" = None,
    ) -> str:
        """Generate a Pascal script that removes ITM records from *plugin_name*."""
        rs = reasoning.conclusion if reasoning else None
        return _xedit_clean_itms(plugin_name, rs)

    def xedit_esl_flag(
        self,
        plugins: List[str],
        reasoning: "Optional[ReasoningResult]" = None,
    ) -> str:
        """Generate a Pascal script that ESL-flags a list of plugins."""
        rs = reasoning.conclusion if reasoning else None
        return _xedit_esl_flag(plugins, rs)

    # ------------------------------------------------------------------ #
    #  INI tweaks                                                         #
    # ------------------------------------------------------------------ #

    def ini_tweak(
        self,
        preset: str,
        reasoning: "Optional[ReasoningResult]" = None,
    ) -> str:
        """
        Generate an INI fragment for *preset*.

        Valid presets: ``papyrus_logging``, ``archive_invalidation``,
        ``performance_high``, ``performance_low``.
        """
        rs = reasoning.conclusion if reasoning else None
        return _ini_tweak(preset, rs)

    # ------------------------------------------------------------------ #
    #  Batch / PowerShell                                                 #
    # ------------------------------------------------------------------ #

    def batch_safe_launch(
        self,
        mo2_path: str = "C:\\Modding\\ModOrganizer2",
        f4se_path: str = "C:\\Games\\Fallout4\\f4se_loader.exe",
        reasoning: "Optional[ReasoningResult]" = None,
    ) -> str:
        """Generate a .bat file that checks plugin count and launches via F4SE."""
        rs = reasoning.conclusion if reasoning else None
        return _bat_safe_launch(mo2_path, f4se_path, rs)

    def batch_backup_profiles(
        self,
        mo2_path: str = "C:\\Modding\\ModOrganizer2",
        backup_root: str = "C:\\Modding\\Backups",
        keep: int = 5,
        reasoning: "Optional[ReasoningResult]" = None,
    ) -> str:
        """Generate a PowerShell script that backs up all MO2 profiles."""
        rs = reasoning.conclusion if reasoning else None
        return _ps1_backup_profiles(mo2_path, backup_root, keep, rs)

    # ------------------------------------------------------------------ #
    #  Reasoning-driven generation                                        #
    # ------------------------------------------------------------------ #

    def from_reasoning(
        self,
        reasoning: "ReasoningResult",
        patch_name: str = "MossyAutoFix",
        plugins: Optional[List[str]] = None,
        conflicts: Optional[List[Dict[str, Any]]] = None,
    ) -> Dict[str, str]:
        """
        Automatically choose and generate the most relevant scripts based on
        a ``ReasoningResult`` from ``ModReasoner``.

        Returns a dict mapping script filename → script content.
        """
        scripts: Dict[str, str] = {}
        rules_fired = {s.rule for s in reasoning.steps}

        # Always generate the conflict-patch script if conflicts are present
        if conflicts or "ConflictRootCause" in rules_fired:
            scripts[f"{_safe_name(patch_name)}_conflict_patch.pas"] = (
                self.xedit_conflict_patch(patch_name, plugins or [], conflicts, reasoning)
            )

        # ESL-flagging when cap is approaching
        if "PluginCapHard" in rules_fired or "PluginCapWarning" in rules_fired:
            if plugins:
                scripts[f"{_safe_name(patch_name)}_esl_flag.pas"] = (
                    self.xedit_esl_flag(plugins, reasoning)
                )

        # Papyrus logging for crash / script-lag diagnoses
        if any(r in rules_fired for r in ("CrashDiagnosis", "ScriptLagDiagnosis")):
            scripts["enable_papyrus_logging.ini"] = self.ini_tweak(
                "papyrus_logging", reasoning
            )

        # Safe-launch batch if F4SE dependency is flagged
        if "F4SEDependency" in rules_fired:
            scripts["safe_launch.bat"] = self.batch_safe_launch(reasoning=reasoning)

        # Always include archive invalidation tweak as a best-practice extra
        if "MissingTextureDiagnosis" in rules_fired:
            scripts["archive_invalidation.ini"] = self.ini_tweak(
                "archive_invalidation", reasoning
            )

        # Fallback: generic conflict patch
        if not scripts:
            scripts[f"{_safe_name(patch_name)}_patch.pas"] = (
                self.xedit_conflict_patch(patch_name, plugins or [], conflicts, reasoning)
            )

        return scripts

    # ------------------------------------------------------------------ #
    #  File I/O                                                           #
    # ------------------------------------------------------------------ #

    def write(
        self,
        filename: str,
        content: str,
        output_dir: Optional[Path] = None,
    ) -> Path:
        """Write *content* to *filename* inside *output_dir* (or the default)."""
        dest_dir = Path(output_dir) if output_dir else self.output_dir
        dest_dir.mkdir(parents=True, exist_ok=True)
        out = dest_dir / filename
        out.write_text(content, encoding="utf-8")
        logger.info(f"Script written: {out}")
        return out

    def write_all(
        self,
        scripts: Dict[str, str],
        output_dir: Optional[Path] = None,
    ) -> List[Path]:
        """Write a dict of filename → content, returning the list of paths."""
        return [self.write(name, content, output_dir) for name, content in scripts.items()]
